name: platform_ui
description: Platform specific Widgets and UI toolkit
version: 0.2.1
homepage: https://github.com/iBog/platform_ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter    
  fluent_ui: ^4.7.6
  macos_ui: ^2.0.0
  libadwaita: ^2.0.2
  adwaita: ^1.1.0
  libadwaita_core: ^0.5.4
  popover_gtk: ^0.2.6+3
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  intl_utils: ^2.8.4

dependency_overrides:
  collection: 1.18.0